spring:
  application:
    name: service-hi
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          group: test-1
          destination: test
          # 消费者数量
          concurrency: 3
          # 消息最大重试次数 默认3
          #maxAttempts: 3
        output:
          destination: test
      rabbit:
        bindings:
          input:
            consumer:
              maxConcurrency: 3
              bindingRoutingKey: a.#
              # ack模式 NONE MANUAL AUTO
              acknowledgeMode: MANUAL


