eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
#    api-a:
#      path: /
#      serviceId: https://www.baidu.com/
    hi: # 仅仅是个名字 path才是路由规则
      path: /ha/**
      serviceId: service-hi