spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ismeade/spring-cloud-examples
          searchPaths: config-repo
#          username: ********
#          password: ********
#          basedir: 配置文件临时目录
#      label: master
# 需要引入spring-boot-starter-security
security:
  user:
    name: user
    password: 1234567
server:
  port: 8888

# 读取application-{value}.tml/properties配置文件，还可以通过环境变量覆盖这个这是
spring:
  profiles:
    active: uat
